name: tdd_cac1
description: "Flutter TDD and Clean Architecture Course [1]"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it: ^7.7.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  http: ^1.2.2
  dartz: ^0.10.1
  shared_preferences: ^2.3.2
  data_connection_checker_nulls: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
